name: kicad pcb ops CI

on:
  push:
    paths:
    - 'hardware/boards/mainboard/Mainboard.kicad_pcb'
    - 'hardware/boards/mainboard/**.sch'
    - 'hardware/boards/knobs-controller/knobs.kicad_pcb'
    - 'hardware/boards/knobs-controller/**.sch'
    - '.github/workflows/**'

jobs:
  
  mainboard:
    runs-on: ubuntu-latest
    name: build-mainboard-artifact
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: package schematic and pcbs
      id: hello
      uses: newdigate/kicad-github-action@v0.4.1
      with:
        kicad-project-path: "hardware/boards/mainboard"
        kicad-schematic-filename: "Mainboard.sch"
        kicad-board-filename: "Mainboard.kicad_pcb"
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mainboard-artifact
        path: output

  breakout:
    runs-on: ubuntu-latest
    name: build-breakout-artifact
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: package schematic and pcbs
      id: hello
      uses: newdigate/kicad-github-action@v0.4.1
      with:
        kicad-project-path: "hardware/boards/knobs-controller"
        kicad-schematic-filename: "knobs.sch"
        kicad-board-filename: "knobs.kicad_pcb"
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: breakout-artifact
        path: output
